server.port=8090
gymbro.backend.url=http://localhost:8080
gymbro.jwt.secret=${JWT_SECRET:supersecret_noone_will_get_out}
gymbro.bdui.m2m.issuer=${BDUI_M2M_JWT_ISS:gymbro-bdui}
gymbro.bdui.m2m.audience=${BDUI_M2M_JWT_AUD:gymbro-workouts}
gymbro.bdui.m2m.ttl-seconds=${BDUI_M2M_TTL_SEC:300}
gymbro.bdui.m2m.private-key-pem=${BDUI_M2M_JWT_PRIVATE_KEY_PEM:}
