server.port=8090
gymbro.backend.url=http://localhost:8080
gymbro.jwt.secret=${JWT_SECRET:supersecret_noone_will_get_out}
gymbro.bdui.to.workouts.secret=${BDUI_TO_WORKOUTS_SECRET:bdui_to_workouts_dev_change_me}
