services:
  postgres_analytics_test:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymbro_analytics_test
    ports:
      - "5546:5432"
    volumes:
      - ../services/analytics/db/migrations:/docker-entrypoint-initdb.d:ro

  postgres_feeds_test:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymbro_feeds_test
    ports:
      - "5547:5432"
    volumes:
      - ../services/feeds/db/migrations:/docker-entrypoint-initdb.d:ro

  postgres_perks_test:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymbro_perks_test
    ports:
      - "5548:5432"
    volumes:
      - ../services/perks/db/migrations:/docker-entrypoint-initdb.d:ro

